### ISSUE TITLE
Different site

### ISSUE THREAD

**Issue by rugk** [wybiral/localtoast#6]
This is not https://wybiral.github.io/wtf/ you've linked from Twitter.

This seems to be the debugging version rather.

Maybe you can cross-link the sites https://wybiral.github.io/localtoast/ and https://wybiral.github.io/wtf/.

**Comment by rugk** [comment]
and https://wybiral.github.io/steam-block/… uhm… how many sites do you have?

**Comment by wybiral** [comment]
They're all different things even though they use a similar technique.

The `/wtf/` one is a demo of it being used in a semi-practical (albeit creepy and invasive) way to give recommendations.

The `/localtoast/` one is more of a reference of different services that can be discovered using this technique.

And the `/steam-block/` one specifically targets the Steam IPC port to block the application on Linux.

**Comment by rugk** [comment]
Well·… yeah, but when you are on one site, you may also like the other ones (that e.g. give you detailed infos). Do you understand what I mean?

**Comment by rugk** [comment]
Solved?

**Comment by wybiral** [comment]
It's not an issue. They're independent projects meant as references or demos. Nobody would learn anything more from seeing one than from seeing the other (same underlying tech).

If they want to see more of my experiments they can check my GitHub page or follow me on Twitter.
